# Generated by Django 3.0 on 2019-12-05 10:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Вид расчета',
                'verbose_name_plural': 'Виды расчета',
            },
        ),
        migrations.AlterModelOptions(
            name='contracttype',
            options={'verbose_name': 'Вид договора', 'verbose_name_plural': 'Виды договоров'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='date',
        ),
        migrations.AddField(
            model_name='order',
            name='customer_address',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name='Адрес заказчика'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.CharField(default='Клиент', max_length=100, verbose_name='ФИО заказчика'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(default='223322', max_length=15, verbose_name='Телефон заказчика'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='order.ContractType', verbose_name='Вид договора'),
        ),
    ]
